theme: jekyll-theme-architect
title: A.J. - Full-Stack Software Engineer
minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
    stackoverflow: "11111"
    dribbble: jekyll
    facebook: jekyll
    flickr: jekyll
    instagram: jekyll
    linkedin: jekyll
    pinterest: jekyll
    telegram: jekyll
    microdotblog: jekyll
    keybase: jekyll
author:
  name: Arthur 'A.J.' Hutchins
  email: "aj.hutchins16@gmail.com"
